[package]
name = "primeex_nativeprime"
version = "0.1.0"
authors = []

[lib]
name = "primeex_nativeprime"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.14.0"
rustler_codegen = "0.14.0"
lazy_static = "0.2"
primal = "0.2.3"
